# This is a basic workflow to help you get started with Actions

name: v2_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Show Details
      run: echo "GITHUB_RUN_NUMBER=${{ github.run_number }}"
    - name: Build Umbraco package
      run: .\build\Build-Release.ps1 -ReleaseVersionNumber "2.1.0" -PreReleaseName "-alpha.${{ github.run_number }}"
      shell: powershell
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: NugetPackages
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}\build\Release\**\*.nupgk
